name: sample-android-build.yml

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  sample-android-build:
    name: Build Android App
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sample/android

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: ./gradlew assembleDebug
