name: lib-debug-build.yml

on:
  push:
    branches: ['main']
    paths: ['lib/**']
  pull_request:
    branches: ['main']
    paths: ['lib/**']
  workflow_dispatch:

jobs:
  debug-android-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install CMake (if not present)
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Debug - Show environment
        run: |
          echo "=== Environment Info ==="
          echo "OS: $(uname -a)"
          echo "Working directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Lib directory contents:"
          ls -la lib/

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android NDK
        uses: android-actions/setup-android@v2

      - name: Debug - Show Android environment
        run: |
          echo "=== Android Environment ==="
          echo "ANDROID_HOME: $ANDROID_HOME"
          echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
          echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
          echo "PATH: $PATH"
          echo "NDK version:"
          $ANDROID_NDK_HOME/ndk-build --version || echo "ndk-build not found"
          echo "CMake version:"
          cmake --version || echo "CMake not found"

      - name: Debug - Test single Android build
        run: |
          echo "=== Testing Single Android Build ==="
          cd lib
          mkdir -p build-android
          cd build-android
          
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -DCMAKE_BUILD_TYPE=Debug \
            -DANDROID_STL=c++_shared
          
          echo "=== CMake configuration completed ==="
          
          # Try to build
          make VERBOSE=1 || echo "Build failed, but continuing for debugging"
          
          echo "=== Build attempt completed ==="
          
          # Show what was created
          echo "=== Build artifacts ==="
          find . -type f -name "*.so" -o -name "*.a" -o -name "*.o" | head -10
          ls -la || echo "No files in build directory"

      - name: Debug - Show build logs
        if: always()
        run: |
          echo "=== Build Directory Contents ==="
          find lib/build-android -type f 2>/dev/null | head -20 || echo "No build directory found"
          
          echo "=== CMake Cache ==="
          cat lib/build-android/CMakeCache.txt 2>/dev/null | head -50 || echo "No CMake cache found"
          
          echo "=== CMake Error Log ==="
          cat lib/build-android/CMakeError.log 2>/dev/null | head -50 || echo "No CMake error log found"

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-android-build-logs
          path: |
            lib/build-android/
            lib/CMakeLists.txt
            lib/version.h
          retention-days: 7 