name: sample-ios-build.yml

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  sample-ios-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Inspect .pbxproj file content
        run: |
          cat sample/llvp/llvp.xcodeproj/project.pbxproj
      
      #- run: pod install --project-directory=sample/llvp

      - name: Check Path
        run: xcrun xcode-select --print-path
      - name: Present Working Directory
        run: pwd
      - name: Double-check macOS version
        run: sw_vers
      - name: Double-check Xcode.app selected
        run: xcode-select --print-path
      - name: Check xcodebuild version
        run: xcodebuild -version
      - name: Check xcode embedded SDKs
        run: xcodebuild -showsdks
      - name: Show buildable schemes
        run: xcodebuild -list

      - run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - run: |
          xcodebuild clean build \
            -project sample/llvp/llvp.xcodeproj \
            -scheme llvp \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
