name: sample-ios-build

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  sample-ios-build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Print macOS and Xcode environment info
        run: |
          sw_vers
          xcode-select --print-path
          xcodebuild -version
          xcodebuild -showsdks

      - name: List available Xcode schemes
        run: xcodebuild -list -project sample/llvp/llvp.xcodeproj

      - run: |
          xcodebuild clean build \
            -project sample/llvp/llvp.xcodeproj \
            -scheme llvp \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
