name: sample-android-build.yml

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  sample-android-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: ./gradlew assembleDebug
        working-directory: sample/android
